spring:
  cloud:
    gateway:
      routes:
        - id: get_route
          uri: https://httpbin.org:80
          predicates:
            - Path=/get
        - id: auth_service_route
          uri: lb://auth-service
          predicates:
            - Path=/test-dev/**
        - id: eff_service_route
          uri: lb://eff-service
          predicates:
            - Path=/eff/**
