spring:
  cloud:
    gateway:
      routes:
        - id: get_route
          uri: http://httpbin.org:80
          predicates:
            - Path=/get
        - id: auth_service_route
          uri: lb://auth-service
          predicates:
            - Path=/user-dev/**
          filters:
            - RewritePath=/user-dev/(?<segment>.*), /$\{segment}
        - id: eff_service_route
          uri: lb://eff-service
          predicates:
            - Path=/eff/**
          filters:
            - RewritePath=/eff/(?<segment>.*), /$\{segment}
